# Generated by Django 4.0.2 on 2022-02-03 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id_Checklist', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion_checklist', models.DateField(auto_now_add=True)),
                ('fecha_plazo_checklist', models.DateField()),
                ('nombre_checklist', models.CharField(max_length=250)),
                ('descripcion_checklist', models.CharField(max_length=250)),
                ('favorito_checklist', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'checklist',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_actividad', models.CharField(max_length=250)),
                ('descripcion_actividad', models.CharField(max_length=500)),
                ('actividad_realizada', models.BooleanField(default=False)),
                ('id_checklist', models.ForeignKey(db_column='id_Checklist', on_delete=django.db.models.deletion.DO_NOTHING, to='ChecklistApp.checklist')),
            ],
            options={
                'db_table': 'actividad',
            },
        ),
    ]
