# Generated by Django 4.0.2 on 2022-02-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistApp', '0002_rename_id_checklist_checklist_id_checklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='favorito_checklist',
            new_name='favorito',
        ),
        migrations.RenameField(
            model_name='checklist',
            old_name='fecha_creacion_checklist',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='checklist',
            old_name='fecha_plazo_checklist',
            new_name='fecha_plazo',
        ),
    ]
