# Generated by Django 4.0.2 on 2022-02-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistApp', '0003_rename_favorito_checklist_checklist_favorito_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='checklist',
            options={'managed': False},
        ),
    ]
