# Generated by Django 4.0.2 on 2022-02-04 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistApp', '0004_alter_actividad_options_alter_checklist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={},
        ),
    ]
