# Generated by Django 4.0.2 on 2022-02-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistApp', '0005_alter_checklist_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='fecha_plazo',
            field=models.DateTimeField(),
        ),
    ]
