# Generated by Django 4.0.2 on 2022-02-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistApp', '0006_alter_checklist_fecha_plazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='fecha_plazo',
            field=models.DateField(),
        ),
    ]
