# Generated by Django 4.0.2 on 2022-02-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistApp', '0007_alter_checklist_fecha_plazo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={},
        ),
    ]
