# Generated by Django 4.0.2 on 2022-02-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistApp', '0008_alter_actividad_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='descripcion_actividad',
            field=models.TextField(max_length=500),
        ),
    ]
