# Generated by Django 4.0.2 on 2022-02-04 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistApp', '0009_alter_actividad_descripcion_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='id_checklist',
            field=models.ForeignKey(db_column='id_Checklist', on_delete=django.db.models.deletion.CASCADE, to='ChecklistApp.checklist'),
        ),
    ]
