# Generated by Django 4.0.2 on 2022-02-04 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistApp', '0011_alter_actividad_id_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='id_checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChecklistApp.checklist'),
        ),
    ]
