# Generated by Django 4.0.2 on 2022-02-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistApp', '0013_alter_actividad_id_checklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='favorito',
        ),
        migrations.AlterField(
            model_name='checklist',
            name='descripcion_checklist',
            field=models.TextField(max_length=250),
        ),
    ]
