# Generated by Django 4.0.2 on 2022-02-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistApp', '0014_remove_checklist_favorito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='fecha_plazo',
            field=models.CharField(max_length=250),
        ),
    ]
